let all_interactions = [ //TODO: Refactor these :):):)
  [["effigy", "demon", "oni", "yurei", "chimera"], "Flick Light Switch On/Off", "On/Off"],
  [["effigy", "rusalka", "demon", "shade", "oni"], "Turn Radio On/Off", "On/Off"],
  [[], "Turn Alarm On/Off", "On/Off"],
  [["effigy", "rusalka", "demon", "shade", "oni", "yurei", "mare"], "Knock Book Off Bookshelf", "Object Movement"],
  [["effigy", "rusalka", "shade", "oni", "yurei", "mare"], "Blow Out Candle", "Humane Action"],
  [["effigy", "rusalka", "demon", "chimera"], "Turn Breaker On/Off", "On/Off"],
  [["effigy", "rusalka", "demon", "oni", "chimera"], "Stab Bloody Knife In Wall", "Knife-Related"],
  [["yurei", "mare"], "Smash Wall", "Violent Action"],
  [["effigy", "rusalka", "demon", "shade", "oni", "chimera"], "Open/Close Door", "Open/Close"],
  [[], "Rock Rocking Chair", "Smash"],
  [["effigy", "rusalka", "demon", "shade", "oni", "mare", "chimera"], "Turn Television On/Off", "On/Off"],
  [["effigy", "rusalka", "demon", "shade", "oni", "mare", "chimera"], "Turn Kettle On/Off", "On/Off"],
  [["effigy", "rusalka", "demon", "shade", "oni", "mare"], "Knock Painting Off Wall", "Object Movement"],
  [["effigy", "rusalka", "demon", "shade", "oni", "mare"], "String Ukulele", "Humane Action"],
  [[], "Ring Mobile Phone", "Humane Action"],
  [["effigy", "demon", "oni", "yurei"], "Throw Bloody Knife at Hunter", "Knife-Related"],
  [["effigy", "demon", "oni", "mare", "chimera"], "Smash Bottle", "Violent Action"],
  [["effigy", "rusalka", "demon"], "Play With Kids Ball", "Toy-Related"],
  [["demon"], "Move Kids Ball", "Toy-Related"],
  [["oni", "yurei", "mare"], "Throw Kids Ball", "Toy-Related"],
  [["effigy", "rusalka", "demon", "oni"], "Throw Kids Toy", "Toy-Related"],
  [["rusalka", "demon", "shade", "oni"], "Move Kids Toy", "Toy-Related"],
  [["yurei"], "Throw Kids Dino Toy", "Toy-Related"],
  [["chimera"], "Move Kids Dino Toy", "Toy-Related"],
  [["effigy", "demon", "oni", "yurei", "mare", "chimera"], "Throw/Smash Plate", "Violent Action"],
  [["effigy", "demon", "mare"], "Place Crucifix on Wall", "Crucifix, Pentagram and/or Grave-Related"],
  [["demon", "oni", "yurei"], "Place Crucifix Outside House", "Crucifix, Pentagram and/or Grave-Related"],
  [["effigy", "demon", "yurei"], "Dig Grave Outside House", "Crucifix, Pentagram and/or Grave-Related"],
  [["effigy", "rusalka", "demon", "mare"], "Change Players Flashlight", "Manipulation"],
  [["chimera"], "Disable Players Flashlight", "Manipulation"],
  [["effigy", "oni", "mare"], "Kill Houseplant", "Humane Action"],
  [["effigy", "rusalka", "demon", "oni"], "Lock Door", "Humane Action"],
  [["effigy", "rusalka", "demon", "oni", "yurei"], "Float Painting Down Hallway", "Object Movement"],
  [["mare"], "Flip Painting Upside Down", "Object Movement"],
  [["effigy", "rusalka", "demon", "oni"], "Pin Chair To Ceiling", "Object Movement"],
  [["effigy", "rusalka", "demon", "oni"], "Steal Household Item", "Humane Action"],
  [["mare"], "Steal All Paintings", "Humane Action"],
  [["mare"], "Steal All Rugs", "Humane Action"],
  [["rusalka", "yurei"], "Lift All Objects In Room", "Object Movement"],
  [["rusalka", "shade", "yurei"], "Write On Mirror", "Humane Action"],
  [["rusalka", "shade", "yurei"], "Disembodied Breathing", "Sound-Related"],
  [["rusalka", "demon", "shade", "oni", "chimera"], "Turn Oven On/Off", "On/Off"],
  [["demon"], "Hissing", "Sound-Related"],
  [["demon", "chimera"], "Place a Pentagram", "Crucifix, Pentagram and/or Grave-Related"],
  [["demon", "oni", "mare"], "Scribble On Painting", "Humane Action"],
  [["shade", "yurei"], "Open Drawer", "Open/Close"],
  [["oni", "yurei", "chimera"], "Blood Writing", "Blood-Related"],
  [["oni", "yurei"], "Rain Blood", "Blood-Related"],
  [["mare"], "Create Pool of Blood", "Blood-Related"],
  [["mare", "chimera"], "Bloody Handprint", "Blood-Related"],
  [["mare"], "Fill Bath with Blood", "Blood-Related"],
  [["mare", "yurei", "chimera"], "Fill Kitchen Sink with Blood", "Blood-Related"],
  [["oni"], "Bruise Player", "Violent Action"],
  [["yurei", "chimera"], "Fill Room with Flies", "Insect-Related"],
  [["mare", "chimera"], "Fill Room with Moths", "Insect-Related"],
  [["mare", "chimera"], "Fill Room with Cockroaches", "Insect-Related"],
  [["mare", "shade"], "Appear as Apparition", "Physical Action"],
  [["yurei"], "Disembodied Crying", "Sound-Related"],
  [["yurei", "mare", "chimera"], "Push Fridge Over", "Object Movement"],
  [["mare"], "Hang Voodoo Doll From Ceiling", "Crucifix, Pentagram and/or Grave-Related"],
  [["chimera"], "Smash Window (Audio Only)", "Sound-Related"],
  [["chimera"], "Fake a Hunt", "Ghostly Action"],
  [["chimera"], "Duplicate Household Item", "Manipulation"],
  [["chimera"], "Spike Players Heart Rate", "Ghostly Action"]
];

/*let all_interactions_refactored = {

}*/