let all_interactions = [
  [["effigy", "demon", "oni", "yurei", "chimera"], "Flick Light Switch On/Off"],
  [["effigy", "rusalka", "demon", "shade", "oni"], "Turn Radio On/Off"],
  [[], "Turn Alarm On/Off"],
  [["effigy", "rusalka", "demon", "shade", "oni", "yurei", "mare"], "Knock Book Off Bookshelf"],
  [["effigy", "rusalka", "shade", "oni", "yurei", "mare"], "Blow Out Candle"],
  [["effigy", "rusalka", "demon", "chimera"], "Turn Breaker On/Off"],
  [["effigy", "rusalka", "demon", "oni", "chimera"], "Stab Bloody Knife In Wall"],
  [["yurei", "mare"], "Smash Wall"],
  [["effigy", "rusalka", "demon", "shade", "oni", "chimera"], "Open/Close Door"],
  [[], "Rock Rocking Chair"],
  [["effigy", "rusalka", "demon", "shade", "oni", "mare", "chimera"], "Turn Television On/Off"],
  [["effigy", "rusalka", "demon", "shade", "oni", "mare", "chimera"], "Turn Kettle On/Off"],
  [["effigy", "rusalka", "demon", "shade", "oni", "mare"], "Knock Painting Off Wall"],
  [["effigy", "rusalka", "demon", "shade", "oni", "mare"], "String Ukulele"],
  [[], "Ring Mobile Phone"],
  [["effigy", "demon", "oni", "yurei"], "Throw Bloody Knife at Hunter"],
  [["effigy", "demon", "oni", "mare", "chimera"], "Smash Bottle"],
  [["effigy", "rusalka", "demon"], "Play With Kids Ball"],
  [["demon"], "Move Kids Ball"],
  [["oni", "yurei", "mare"], "Throw Kids Ball"],
  [["effigy", "rusalka", "demon", "oni"], "Throw Kids Toy"],
  [["rusalka", "demon", "shade", "oni"], "Move Kids Toy"],
  [["yurei"], "Throw Kids Dino Toy"],
  [["chimera"], "Move Kids Dino Toy"],
  [["effigy", "demon", "oni", "yurei", "mare", "chimera"], "Throw/Smash Plate"],
  [["effigy", "demon", "mare"], "Place Crucifix on Wall"],
  [["demon", "oni", "yurei"], "Place Crucifix Outside House"],
  [["effigy", "demon", "yurei"], "Dig Grave Outside House"],
  [["effigy", "rusalka", "demon", "mare"], "Change Players Flashlight"],
  [["chimera"], "Disable Players Flashlight"],
  [["effigy", "oni", "mare"], "Kill Houseplant"],
  [["effigy", "rusalka", "demon", "oni"], "Lock Door"],
  [["effigy", "rusalka", "demon", "oni", "yurei"], "Float Painting Down Hallway"],
  [["mare"], "Flip Painting Upside Down"],
  [["effigy", "rusalka", "demon", "oni"], "Pin Chair To Ceiling"],
  [["effigy", "rusalka", "demon", "oni"], "Steal Household Item"],
  [["mare"], "Steal All Paintings"],
  [["mare"], "Steal All Rugs"],
  [["rusalka", "yurei"], "Lift All Objects In Room"],
  [["rusalka", "shade", "yurei"], "Write On Mirror"],
  [["rusalka", "shade", "yurei"], "Disembodied Breathing"],
  [["rusalka", "demon", "shade", "oni", "chimera"], "Turn Oven On/Off"],
  [["demon"], "Hissing"],
  [["demon", "chimera"], "Place a Pentagram"],
  [["demon", "oni", "mare"], "Scribble On Painting"],
  [["shade", "yurei"], "Open Drawer"],
  [["oni", "yurei"], "Blood Writing"],
  [["oni", "yurei"], "Rain Blood"],
  [["mare"], "Create Pool of Blood"],
  [["mare", "chimera"], "Bloody Handprint"],
  [["mare"], "Fill Bath with Blood"],
  [["mare", "yurei", "chimera"], "Fill Kitchen Sink with Blood"],
  [["oni"], "Bruise Player"],
  [["yurei", "chimera"], "Fill Room with Flies"],
  [["mare", "chimera"], "Fill Room with Moths"],
  [["mare", "chimera"], "Fill Room with Cockroaches"],
  [["mare", "shade"], "Appear as Apparition"],
  [["yurei"], "Lift All Objects in Room"],
  [["yurei"], "Disembodied Crying"],
  [["yurei", "mare", "chimera"], "Push Fridge Over"],
  [["mare"], "Hang Voodoo Doll From Ceiling"],
  [["chimera"], "Smash Window (Audio Only)"],
  [["chimera"], "Fake a Hunt"],
  [["chimera"], "Duplicate Household Item"],
  [["chimera"], "Spike Players Heart Rate"]
];