let all_interaction_categories = {
  "On/Off": ["Flick Light Switch On/Off","Turn Radio On/Off","Turn Alarm On/Off","Turn Breaker On/Off","Turn Television On/Off","Turn Kettle On/Off","Turn Oven On/Off"],
  "Open/Close": ["Open/Close Door", "Open/Close Drawer"],
  "Object Movement": ["Knock Book Off Bookshelf","Knock Painting Off Wall","Flip Painting Upside Down","Float Painting Down Hallway","Pin Chair to Ceiling","Lift All Objects in Room", "Push Fridge Over"],
  "Humane Action": ["Blow out Candle","Rock Rocking Chair","String Ukulele","Ring Mobile Phone","Steal All Paintings","Steal All Rugs","Lock Door","Kill Houseplant", "Steal Household Item", "Write on Mirror", "Scribble on Painting"],
  "Knife-Related": ["Stab Bloody Knife In Wall","Throw Bloody Knife"],
  "Violent Action": ["Smash Wall","Throw/Smash Bottle","Throw/Smash Plate","Bruise Player"],
  "Toy-Related": ["Move Toy Ball","Throw Toy","Move Toy"],
  "Ghostly Action": ["Spike Players Heartrate","Fake a Hunt"],
  "Manipulation": ["Duplicate Household Item","Disable Players Flashlight", "Change Players Flashlight"],
  "Sound-Related": ["Smash Window (Audio Only)","Disembodied Crying (Not Baby)","Hissing","Disembodied Breathing"],
  "Crucifix, Pentagram and/or Grave-Related": ["Hang Voodoo Doll from Ceiling","Place Crucifix on Wall","Place Crucifix outside House","Dig Grave Outside House", "Place a Pentagram"],
  "Physical Action": ["Appear as Apparition"],
  "Blood-Related": ["Create Pool of Blood","Rain Blood","Fill Bath with Blood", "Blood Writing", "Bloody Handprint", "Fill Kitchen Sink with Blood"],
  "Insect-Related": ["Fill Room with Cockroaches","Fill Room with Moths","Fill Room with Flies"]
}

let all_interaction_ghost_types = {
    "Disable Players Flashlight": {ghost_types:{"chimera":{rarity:"e-rare"}}},
    "Change Players Flashlight": {ghost_types:{"effigy":{rarity:"rare"}, "rusalka":{rarity:"e-rare"},"demon":{rarity:"uncommon"},"mare":{rarity:"uncommon"}}},
    "Steal Household Item": {ghost_types:{"effigy":{rarity:"e-rare"},"rusalka":{rarity:"rare"},"demon":{rarity:"uncommon"},oni:{rarity:"common"}}},
    "Write on Mirror":{ghost_types:{"rusalka":{rarity:"rare"},"shade":{rarity:"uncommon"},"yurei":{rarity:"uncommon"}}},
    "Disembodied Breathing":{ghost_types:{"rusalka":{rarity:"rare"},"shade":{rarity:"uncommon"},"yurei":{rarity:"uncommon"}}},
    "Turn Oven On/Off":{ghost_types:{"rusalka":{rarity:"e-rare"},"demon":{rarity:"common"},"shade":{rarity:"rare"},"oni":{rarity:"uncommon"},"chimera":{rarity:"common"}}},
    "Place a Pentagram":{ghost_types:{"demon":{rarity:"e-rare"},"chimera":{rarity:"rare"}}},
    "Scribble on Painting": {ghost_types:{"demon":{rarity:"e-rare"},"oni":{rarity:"rare"},"mare":{rarity:"uncommon"}}},
    "Open/Close Drawer":{ghost_types:{"shade":{rarity:"rare"},"yurei":{rarity:"e-rare"}}},
    "Blood Writing":{ghost_types:{"oni":{rarity:"rare"},"yurei":{rarity:"rare"},"chimera":{rarity:"common"}}},
    "Bloody Handprint":{ghost_types:{"mare":{rarity:"e-rare"},"chimera":{rarity:"uncommon"}}},
    "Fill Kitchen Sink with Blood": {ghost_types:{"mare":{rarity:"e-rare"},"yurei":{rarity:"rare"},"chimera":{rarity:"common"}}},
    "Push Fridge Over":{ghost_types:{"yurei":{rarity:"e-rare"},"mare":{rarity:"rare"},"chimera":{rarity:"rare"}}},
    "Flick Light Switch On/Off": {ghost_types: {"effigy": {rarity: "common"},"demon": {rarity: "common"},"shade": {rarity: "uncommon"},"oni": {rarity: "rare"},"yurei": {rarity: "rare"},"chimera": {rarity: "common"}}},
    "Turn Radio On/Off": {ghost_types: {"effigy": {rarity: "common"},"rusalka": {rarity: "e-rare"},"demon": {rarity: "common"},"shade": {rarity: "uncommon"},"oni": {rarity: "rare"}}},
    "Turn Alarm On/Off": {ghost_types: {"effigy": {rarity: "common"},"rusalka": {rarity: "e-rare"},"demon": {rarity: "common"},"shade": {rarity: "uncommon"},"oni": {rarity: "rare"},"yurei": {rarity: "common"},"mare": {rarity: "common"},"chimera": {rarity: "common"}}},
    "Turn Breaker On/Off": {ghost_types: {"effigy": {rarity: "uncommon"},"rusalka": {rarity: "rare"},"demon": {rarity: "common"},"oni": {rarity: "e-rare"},"chimera": {rarity: "uncommon"}}},
    "Turn Television On/Off": {ghost_types: {"effigy": {rarity: "uncommon"},"rusalka": {rarity: "e-rare"},"demon": {rarity: "common"},"shade": {rarity: "rare"},"oni": {rarity: "uncommon"},"mare": {rarity: "uncommon"},"chimera": {rarity: "common"}}},
    "Turn Kettle On/Off": {ghost_types: {"effigy": {rarity: "uncommon"},"rusalka": {rarity: "e-rare"},"demon": {rarity: "common"},"shade": {rarity: "rare"},"oni": {rarity: "uncommon"},"yurei": {rarity: "common"},"mare": {rarity: "uncommon"},"chimera": {rarity: "common"}}},
    "Open/Close Door": {ghost_types: {"effigy": {rarity: "uncommon"},"rusalka": {rarity: "e-rare"},"demon": {rarity: "common"},"shade":{rarity:"e-rare"},"oni": {rarity: "rare"},"chimera": {rarity: "rare"}}},
    "Knock Book Off Bookshelf": {ghost_types: {"effigy":{rarity:"common"}, "rusalka":{rarity:"e-rare"}, "demon":{rarity:"common"}, "shade":{rarity:"uncommon"}, "oni":{rarity:"rare"}, "yurei":{rarity:"uncommon"}, "mare":{rarity:"common"}}},
    "Knock Painting Off Wall": {ghost_types: {"effigy":{rarity:"uncommon"}, "rusalka":{rarity:"e-rare"}, "demon":{rarity:"common"}, "shade":{rarity:"rare"}, "oni":{rarity:"uncommon"}, "mare":{rarity:"rare"}}},
    "Flip Painting Upside Down": {ghost_types:{"mare":{rarity:"rare"}}},
    "Float Painting Down Hallway": {ghost_types: {"effigy": {rarity: "e-rare"},"rusalka": {rarity: "uncommon"},"demon": {rarity: "rare"},"oni": {rarity: "common"},"yurei": {rarity: "uncommon"}}},
    "Pin Chair to Ceiling":{ghost_types:{"effigy":{rarity:"e-rare"}, "rusalka":{rarity:"common"}, "demon":{rarity:"e-rare"}, "oni":{rarity:"uncommon"}}},
    "Lift All Objects in Room":{ghost_types:{"rusalka":{rarity:"rare"}, "yurei":{rarity:"rare"}}},
    "Blow out Candle": {ghost_types:{"effigy":{rarity:"common"}, "rusalka":{rarity:"uncommon"}, "shade":{rarity:"e-rare"}, "oni":{rarity:"rare"}, "yurei":{rarity:"uncommon"}, "mare":{rarity:"e-rare"}}},
    "Rock Rocking Chair": {ghost_types: {"effigy": {rarity: "uncommon"},"rusalka": {rarity: "e-rare"},"demon": {rarity: "uncommon"},"shade": {rarity: "common"},"oni": {rarity: "uncommon"},"yurei": {rarity: "uncommon"},"mare": {rarity: "common"},"chimera": {rarity: "common"}}},
    "String Ukulele": {ghost_types: {"effigy":{rarity:"uncommon"}, "rusalka":{rarity:"e-rare"}, "demon":{rarity:"common"}, "shade":{rarity:"rare"}, "oni":{rarity:"common"}, "mare":{rarity:"common"}}},
    "Ring Mobile Phone": {ghost_types: {"effigy": {rarity: "uncommon"},"rusalka": {rarity: "e-rare"},"demon": {rarity: "common"},"shade": {rarity: "common"},"oni": {rarity: "uncommon"},"yurei": {rarity: "common"},"mare": {rarity: "common"},"chimera": {rarity: "common"}}},
    "Steal All Paintings": {ghost_types:{"mare":{rarity:"rare"}}},
    "Steal All Rugs": {ghost_types:{"mare":{rarity:"rare"}}},
    "Lock Door":{ghost_types:{"effigy":{rarity:"rare"}, "rusalka":{rarity:"e-rare"}, "demon":{rarity:"uncommon"}, "oni":{rarity:"uncommon"}}},
    "Kill Houseplant":{ghost_types:{"effigy":{rarity:"rare"}, "oni":{rarity:"uncommon"}, "mare":{rarity:"e-rare"}}},
    "Stab Bloody Knife In Wall": {ghost_types:{"effigy":{rarity:"uncommon"}, "rusalka":{rarity:"rare"}, "demon":{rarity:"rare"}, "oni":{rarity:"e-rare"},"chimera":{rarity:"uncommon"}}},
    "Throw Bloody Knife":{ghost_types:{"effigy":{rarity:"uncommon"}, "demon":{rarity:"common"}, "oni":{rarity:"common"}, "yurei":{rarity:"common"}}},
    "Smash Wall": {ghost_types:{"yurei":{rarity:"e-rare"}, "mare":{rarity:"uncommon"}}},
    "Throw/Smash Bottle": {ghost_types:{"effigy":{rarity:"rare"}, "demon":{rarity:"uncommon"}, "oni":{rarity:"e-rare"}, "mare":{rarity:"common"}, "chimera":{rarity:"uncommon"}}},
    "Throw/Smash Plate": {ghost_types:{"effigy":{rarity:"rare"}, "demon":{rarity:"uncommon"}, "oni":{rarity:"common"}, "yurei":{rarity:"common"},"mare":{rarity:"uncommon"}, "chimera":{rarity:"uncommon"}}},
    "Bruise Player": {ghost_types:{"oni":{rarity:"e-rare"}}},
    "Move Toy Ball": {ghost_types: {"effigy": {rarity: "rare"},"rusalka": {rarity: "common"},"demon": {rarity: "e-rare"},"oni": {rarity: "uncommon"},"yurei": {rarity: "uncommon"},"mare": {rarity: "uncommon"}}},
    "Throw Toy": {ghost_types: {"effigy": {rarity: "rare"},"rusalka": {rarity: "e-rare"},"demon": {rarity: "rare"},"oni": {rarity: "common"},"yurei": {rarity: "common"}}},
    "Move Toy": {ghost_types: {"rusalka": {rarity: "common"},"shade": {rarity: "common"},"oni": {rarity: "uncommon"},"chimera": {rarity: "common"}}},
    "Spike Players Heartrate": {ghost_types:{"chimera":{rarity:"e-rare"}}},
    "Fake a Hunt": {ghost_types:{"chimera":{rarity:"e-rare"}}},
    "Duplicate Household Item": {ghost_types:{"chimera":{rarity:"e-rare"}}},
    "Smash Window (Audio Only)": {ghost_types:{"chimera":{rarity:"rare"}}},
    "Disembodied Crying (Not Baby)": {ghost_types:{"yurei":{rarity:"e-rare"}}},
    "Hissing": {ghost_types:{"demon":{rarity:"rare"}}},
    "Hang Voodoo Doll from Ceiling": {ghost_types:{"mare":{rarity:"rare"}}},
    "Place Crucifix on Wall": {ghost_types:{"effigy":{rarity:"rare"},"demon":{rarity:"rare"},"mare":{rarity:"e-rare"}}},
    "Place Crucifix outside House": {ghost_types:{"demon":{rarity:"rare"},"oni":{rarity:"rare"},"yurei":{rarity:"uncommon"}}},
    "Dig Grave Outside House": {ghost_types:{"effigy":{rarity:"rare"},"demon":{rarity:"uncommon"},"yurei":{rarity:"uncommon"}}},
    "Appear as Apparition": {ghost_types:{"mare":{rarity:"e-rare"}}},
    "Create Pool of Blood": {ghost_types:{"mare":{rarity:"rare"}}},
    "Rain Blood": {ghost_types:{"oni":{rarity:"rare"}}},
    "Fill Bath with Blood":{ghost_types:{"mare":{rarity:"uncommon"}}},
    "Fill Room with Cockroaches": {ghost_types:{"mare":{rarity:"rare"},"chimera":{rarity:"uncommon"}}},
    "Fill Room with Moths": {ghost_types:{"mare":{rarity:"uncommon"},"chimera":{rarity:"rare"}}},
    "Fill Room with Flies": {ghost_types:{"yurei":{rarity:"rare"},"chimera":{rarity:"rare"}}}
}